version: '3'

services:
  data_layer:
    build:
      context: ./dataLayer  # Path to the directory containing the Dockerfile for dataLayer
    ports:
      - "8000:8000"
    depends_on:
      - redis

  business_layer:
    build:
      context: ./businessLayer  # Path to the directory containing the Dockerfile for businessLayer
    ports:
      - "8001:8001"
    depends_on:
      - data_layer

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
