# Generated by Django 5.0 on 2024-02-05 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketproduct',
            name='user',
        ),
        migrations.AddField(
            model_name='basketproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.product'),
        ),
        migrations.AlterField(
            model_name='basketproduct',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_product_set', to='management.basket'),
        ),
    ]
